name: Add git tag
description: Add git tag on current git ref. If tag already exists tag will be moved to current git ref.
inputs:
  tag-name:
    description: Tag name which will be added to git repository
    required: true
  should-tag-with-timestamp:
    description: Add git tag with current timestamp postfix
    required: false
    default: "false"
  github-token:
    description: Personal access token, used for octokit client
    required: true
    default: ${{ github.token }}
runs:
  using: node12
  main: dist/index.js
